# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: "2.0"
info:
  title: test-data
  version: v1
host: my-host.example.com
schemes:
  - "https"
paths:
  /process/{qty}:
    post:
      summary: Process the csv.
      description: This endpoint receives the input csv and sends to VertexAI for Test Data creation.
      consumes:
        - text/plain
      produces:
        - text/plain
      parameters:
        - in: path
          required: true
          name: qty
          type: integer
        - in: header
          name: API_KEY
          description: API_KEY is the key used to authenticate the API call
          type: string
          required: true
        - in: header
          name: User-Agent
          description: User-Agent is used to identify the caller
          type: string
          default: wiki-interface
          required: true
        - in: body
          name: document
          description: Input Document.
          required: true
          schema:
            type: string
            example: |
              first name,last name,email,password,address,zip,ssn
              "John","Smith","jsmith@email.com","P@ssw0rd","123 Main St","12345","111-22-3333"
      responses:
        200:
          description: OK
          schema:
            type: string
            example: |
              "Jane","Doe","jdoe@email.com","P@ssw0rd1","456 Elm St","67890","222-33-4444"
              "Bob","Jones","bjones@email.com","P@ssw0rd2","789 Oak St","09876","333-44-5555"
              "Alice","Brown","abrown@email.com","P@ssw0rd3","1011 Pine St","23456","444-55-6666"
              "Tom","White","twhite@email.com","P@ssw0rd4","1213 Maple St","34567","555-66-7777"
              "Mary","Green","mgreen@email.com","P@ssw0rd5","1415 Birch St","45678","666-77-8888"
              "David","Blue","dblue@email.com","P@ssw0rd6","1617 Cedar St","56789","777-88-9999"
              "Sarah","Orange","sorange@email.com","P@ssw0rd7","1819 Cherry St","67890","888-99-0000"
              "Mark","Yellow","myellow@email.com","P@ssw0rd8","2021 Willow St","78901","999-00-1111"
              "Linda","Indigo","lindigo@email.com","P@ssw0rd9","2223 Oakwood St","89012","101-11-2222"
              "Michael","Violet","mviolet@email.com","P@ssw0rd10","2425 Pinewood St","90123","111-22-3333"
        400:
          description: Bad request
        401:
          description: Access denied
        500:
          description: Internal error