site_name: 'tc-generator'
site_description: 'Gerador de Documento de Testes'
repo_url: https://github.com/qa-tc-generator
edit_uri: edit/main/docs

# Navigation menu
nav:
  - Home: index.md
  - Configuração: config.md
  - Ambiente: env.md
  - Implementação: impl.md
  - Build: build.md
  - Deploy: deploy.md
  - Teste: test.md
  - GCP: gcp.md

plugins:
  - techdocs-core  

copyright: ISC