site_name: 'script-playwright'
site_description: 'Gerador de Scripts de Testes Playwright'
repo_url: https://github.com/script-playwright
edit_uri: edit/main/docs

# Navigation menu
nav:
  - Home: index.md
  - Configuração: config.md
  - Ambiente: env.md
  - Implementação: impl.md
  - Build: build.md
  - Deploy: deploy.md
  - Teste: test.md
  - GCP: gcp.md

plugins:
  - techdocs-core  

copyright: ISC